# Minimal static deploy
[build]
  publish = "."

# Redirect legacy extensions to root
[[redirects]]
  from = "/index.htm"
  to = "/"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
